### ISSUE TITLE
No entra dentro de los objetivos de la entrega, pero está bien definir el atributo alt de las imágenes

### ISSUE THREAD

**Issue by vicenlu** [marnauortega/react-sprint-2#1]
https://www.innovationvisual.com/knowledge/why-image-alt-text-is-important-for-seo

https://github.com/marnauortega/react-sprint-2/blob/f8e847f2992436198d4c5cdfd4378f06fbc69836/src/index.html#L324

**Comment by marnauortega** [comment]
Es cierto, y soy consciente. Ya las he añadido!

En una web para producción siempre añadiría los alt texts.

**Comment by marnauortega** [comment]
Es cierto, y soy consciente. Ya las he añadido!

En una web para producción siempre añadiría los alt texts.
